### PR TITLE
Computers get, put, delete, post are functional

### PR DESCRIPTION
**Pull request by beelarr**
## Status
**READY**

## Migrations
NO

## Description
Verbs work on Computer and validates that all fields are present

## Todos
- [ ] Tests
- [ ] Documentation

## Steps to Test or Reproduce
```
git fetch origin computer
git checkout computer
rails db:migrate
rails db:seed
```

1. GET, POST, PUT without commision_date for ProductTypes table
* Should fail

2. GET, POST, PUT with commision_date after decommision_date for ProductTypes table
* Should fail

3. DELETE Product 
* Should pass

## Impacted Areas in Application
List general components of the application that this PR will affect:

* Computer Table

### CODE REVIEW

**Comment by jsheridanwells** [comment]
The end_date_after_start_date? method in the Computer model breaks if there is no decommissioned date entered when posting. Is there a way that that method can only be called when decommissioned date is present?

**Comment by jsheridanwells** [comment]
Changing the method to this should work:
```
def end_date_after_start_date?
    	if decommission_date
	        if decommission_date < commission_date
	            errors.add :decommission_date, "must be after commision date. . .buckaroo"
	        end
    	end
    end
```

**Comment by beelarr** [comment]
Updated fix from @jsheridanwells

**Comment by jsheridanwells** [comment]
💯

**Pull request merged**
