### PR TITLE
Jw employee resource

### PR DESCRIPTION
**Pull request by jsheridanwells**
## Status
**READY**

## Migrations
NO

## Description
Verbs work on Employees and validates that all fields are present

## Related PRs
List related PRs against other branches:

branch | PR
------ | ------
other_pr_production | [link]()
other_pr_master | [link]()

## Todos
- [ ] Tests
- [ ] Documentation

## Deploy Notes
Notes regarding deployment the contained body of work.  These should note any
db migrations, etc.

## Steps to Test or Reproduce
Outline the steps to test or reproduce the PR here.

```sh
git fetch
git branch -a
git checkout remotes/origin/jw-employee-resource
```

1. 

## Impacted Areas in Application
List general components of the application that this PR will affect:

*

### CODE REVIEW

**Comment by jsheridanwells** [comment]
Fixed error from setting status to false

**Comment by michaellindstromm** [comment]
@jsheridanwells the only thing missing is that when adding an employee as a supervisor, we need to check whether the department already has a supervisor. I suggest creating a private method that checks this before running .save

**Comment by jsheridanwells** [comment]
Fixed employee status problem

**Comment by michaellindstromm** [comment]
👍

**Pull request merged**
